/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedListToolRouteImport } from './routes/_authenticated/list-tool'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPostJobRouteImport } from './routes/_authenticated/post-job'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as CommunitiesSlugRouteImport } from './routes/communities.$slug'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as WorkersIndexRouteImport } from './routes/workers.index'
import { Route as WorkersIdRouteImport } from './routes/workers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListToolRoute = AuthenticatedListToolRouteImport.update({
  id: '/list-tool',
  path: '/list-tool',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostJobRoute = AuthenticatedPostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesSlugRoute = CommunitiesSlugRouteImport.update({
  id: '/communities/$slug',
  path: '/communities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/marketplace/$id',
  path: '/marketplace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIdRoute = WorkersIdRouteImport.update({
  id: '/workers/$id',
  path: '/workers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/list-tool': typeof AuthenticatedListToolRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/post-job': typeof AuthenticatedPostJobRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/workers/$id': typeof WorkersIdRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/workers/': typeof WorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/list-tool': typeof AuthenticatedListToolRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/post-job': typeof AuthenticatedPostJobRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/workers/$id': typeof WorkersIdRoute
  '/communities': typeof CommunitiesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/workers': typeof WorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/list-tool': typeof AuthenticatedListToolRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/post-job': typeof AuthenticatedPostJobRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/communities/$slug': typeof CommunitiesSlugRoute
  '/jobs/$id': typeof JobsIdRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/workers/$id': typeof WorkersIdRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/workers/': typeof WorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/admin'
    | '/dashboard'
    | '/list-tool'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/saved'
    | '/communities/$slug'
    | '/jobs/$id'
    | '/marketplace/$id'
    | '/posts/$id'
    | '/workers/$id'
    | '/communities/'
    | '/jobs/'
    | '/marketplace/'
    | '/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/admin'
    | '/dashboard'
    | '/list-tool'
    | '/messages'
    | '/notifications'
    | '/post-job'
    | '/profile'
    | '/saved'
    | '/communities/$slug'
    | '/jobs/$id'
    | '/marketplace/$id'
    | '/posts/$id'
    | '/workers/$id'
    | '/communities'
    | '/jobs'
    | '/marketplace'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/list-tool'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/post-job'
    | '/_authenticated/profile'
    | '/_authenticated/saved'
    | '/communities/$slug'
    | '/jobs/$id'
    | '/marketplace/$id'
    | '/posts/$id'
    | '/workers/$id'
    | '/communities/'
    | '/jobs/'
    | '/marketplace/'
    | '/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  CommunitiesSlugRoute: typeof CommunitiesSlugRoute
  JobsIdRoute: typeof JobsIdRoute
  MarketplaceIdRoute: typeof MarketplaceIdRoute
  PostsIdRoute: typeof PostsIdRoute
  WorkersIdRoute: typeof WorkersIdRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/list-tool': {
      id: '/_authenticated/list-tool'
      path: '/list-tool'
      fullPath: '/list-tool'
      preLoaderRoute: typeof AuthenticatedListToolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post-job': {
      id: '/_authenticated/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof AuthenticatedPostJobRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/communities/': {
      id: '/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$slug': {
      id: '/communities/$slug'
      path: '/communities/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof CommunitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/marketplace/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/$id': {
      id: '/workers/$id'
      path: '/workers/$id'
      fullPath: '/workers/$id'
      preLoaderRoute: typeof WorkersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedListToolRoute: typeof AuthenticatedListToolRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPostJobRoute: typeof AuthenticatedPostJobRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedListToolRoute: AuthenticatedListToolRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPostJobRoute: AuthenticatedPostJobRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  CommunitiesSlugRoute: CommunitiesSlugRoute,
  JobsIdRoute: JobsIdRoute,
  MarketplaceIdRoute: MarketplaceIdRoute,
  PostsIdRoute: PostsIdRoute,
  WorkersIdRoute: WorkersIdRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  WorkersIndexRoute: WorkersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
